"""Ajout de la colonne 'etat' dans la table mission

Revision ID: 0b040be94e93
Revises: 
Create Date: 2025-01-19 23:18:39.820558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b040be94e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travaux')
    op.drop_table('users')
    op.drop_table('equipes')
    op.drop_table('mission_team')
    op.drop_table('missions')
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('etat')

    op.create_table('missions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('responsable_id', sa.INTEGER(), nullable=False),
    sa.Column('projet', sa.VARCHAR(length=255), nullable=False),
    sa.Column('chef_de_projet', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date_enregistrement', sa.DATETIME(), nullable=True),
    sa.Column('chauffeur', sa.VARCHAR(length=255), nullable=False),
    sa.Column('marque_vehicule', sa.VARCHAR(length=255), nullable=False),
    sa.Column('matricule_vehicule', sa.VARCHAR(length=50), nullable=False),
    sa.Column('designation_travaux', sa.VARCHAR(length=255), nullable=False),
    sa.Column('site_client', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ville_depart', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ville_arrivee', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_debut', sa.DATE(), nullable=False),
    sa.Column('date_fin', sa.DATE(), nullable=False),
    sa.Column('recharge_gasoil', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_team',
    sa.Column('mission_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('mission_id', 'user_id')
    )
    op.create_table('equipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mission_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('idUser', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fonction', sa.VARCHAR(length=50), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cin', sa.VARCHAR(length=40), nullable=False),
    sa.Column('tel', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rib', sa.VARCHAR(length=34), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('travaux',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=100), nullable=False),
    sa.Column('site_client', sa.VARCHAR(length=100), nullable=False),
    sa.Column('depart', sa.VARCHAR(length=100), nullable=False),
    sa.Column('arrivee', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_debut', sa.DATE(), nullable=False),
    sa.Column('date_fin', sa.DATE(), nullable=False),
    sa.Column('recharge_gasoil', sa.FLOAT(), nullable=False),
    sa.Column('mission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
